(function(){
'use strict';
const SCRIPT=document.currentScript;
const DIRECT=!!SCRIPT?.hasAttribute('data-library-direct');
const KEY='library-reference-notice-agreed-v1';
const AR={
  openTitle:'قبل فتح المرجع',
  text:'هذه المراجع مواد دراسية شخصية ومخصّصة للتعلّم، ويجب استخدامها حصريًا في مختبرات تدريبية وبيئات مصرّح بها (منصات التدريب وCTF أو أنظمة تملكها أو لديك إذن كتابي باختبارها). يُمنع استخدامها ضد أي نظام أو شبكة دون تصريح. المواد مقدّمة كما هي دون أي ضمان، وعبدالله ناصر غير مسؤول عن أي إساءة استخدام لها. بالضغط على «أوافق وأتابع» فأنت تقرّ بأنك قرأت هذا التنبيه وتوافق عليه.',
  agree:'أوافق وأتابع', packAgree:'موافق وتحميل', cancel:'إلغاء', close:'إغلاق التنبيه', reminder:'مرجع تعليمي للمختبرات المصرّح بها فقط', blockedTitle:'لم يتم فتح المرجع', blockedText:'يلزم قبول تنبيه الاستخدام قبل عرض هذا المرجع.', back:'العودة للمكتبة'
};
const EN={
  openTitle:'Before you open this reference',
  text:'These references are personal study material and must be used exclusively in training labs and authorized environments (training platforms, CTFs, or systems you own or have written permission to test). Using them against any system or network without authorization is prohibited. Materials are provided as is, without warranty, and Abdullah Nasser is not responsible for any misuse. By clicking “Agree & Continue” you confirm that you have read and accept this notice.',
  agree:'Agree & Continue', packAgree:'Agree & Download', cancel:'Cancel', close:'Close notice', reminder:'Educational reference for authorized labs only', blockedTitle:'Reference not opened', blockedText:'You must accept the usage notice before this reference can be displayed.', back:'Back to library'
};
function langOf(forced){return forced==='ar'||forced==='en'?forced:(document.documentElement.lang||'en').toLowerCase().startsWith('ar')?'ar':'en'}
function copy(lang){return lang==='ar'?AR:EN}
function hasReferenceAgreement(){try{return sessionStorage.getItem(KEY)==='1'}catch(_){return false}}
function storeReferenceAgreement(){try{sessionStorage.setItem(KEY,'1');return sessionStorage.getItem(KEY)==='1'}catch(_){return false}}
function addStyles(){if(document.getElementById('libraryNoticeStyles'))return;const s=document.createElement('style');s.id='libraryNoticeStyles';s.textContent=`
html.library-guard-pending body>*:not(.library-notice-overlay):not(.library-direct-blocked){visibility:hidden!important}
body.library-notice-lock{overflow:hidden!important}
.library-notice-overlay{position:fixed;inset:0;z-index:100000;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(2,2,7,.82);backdrop-filter:blur(8px)}
.library-notice-dialog{width:min(650px,100%);max-height:min(88vh,760px);overflow:auto;background:#111118;color:#f7f5ff;border:1px solid #302d40;border-radius:18px;box-shadow:0 28px 90px rgba(0,0,0,.6);padding:22px;position:relative;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Tahoma,Arial,sans-serif;line-height:1.75}
.library-notice-dialog[dir=rtl]{text-align:right}.library-notice-dialog[dir=ltr]{text-align:left}.library-notice-dialog h2{margin:0 38px 10px 0;font-size:22px;line-height:1.3;color:#f8f6ff}.library-notice-dialog[dir=ltr] h2{margin:0 0 10px 38px}.library-notice-dialog p{margin:0;color:#c8c3d4;font-size:14px}.library-notice-close{position:absolute;inset-block-start:12px;inset-inline-end:12px;width:34px;height:34px;border:1px solid #343143;border-radius:10px;background:#171720;color:#eee9ff;font-size:22px;line-height:1;cursor:pointer}.library-notice-actions{display:flex;gap:10px;justify-content:flex-end;flex-wrap:wrap;margin-top:20px}.library-notice-dialog[dir=rtl] .library-notice-actions{justify-content:flex-start}.library-notice-btn{min-height:42px;padding:8px 15px;border-radius:11px;border:1px solid #343143;font-weight:800;cursor:pointer;background:#171720;color:#f7f5ff}.library-notice-btn.primary{border-color:rgba(155,115,255,.7);background:#5f3fc0}.library-notice-btn:hover{filter:brightness(1.08)}
.library-authorized-reminder{position:sticky;top:0;z-index:5000;height:28px;display:flex;align-items:center;justify-content:center;padding:0 12px;border-bottom:1px solid #2b2938;background:#0d0d13;color:#bdb5cf;font:700 11px/1.2 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Tahoma,Arial,sans-serif;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
body.library-has-authorized-reminder .bar{top:28px!important}
.library-direct-blocked{min-height:100vh;display:grid;place-items:center;padding:22px;background:#09090d;color:#f7f5ff;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Tahoma,Arial,sans-serif}.library-direct-blocked>div{max-width:560px;text-align:center;border:1px solid #2b2938;border-radius:16px;background:#111118;padding:26px}.library-direct-blocked h1{font-size:24px;margin:0 0 8px}.library-direct-blocked p{color:#aaa5ba;margin:0 0 20px}.library-direct-blocked a{display:inline-flex;min-height:42px;align-items:center;justify-content:center;padding:8px 16px;border:1px solid rgba(155,115,255,.55);border-radius:11px;background:#171721;color:#d8caff;text-decoration:none;font-weight:800}
@media(max-width:1024px){.library-authorized-reminder{font-size:12px}.library-notice-close{width:44px;height:44px}.library-notice-btn{min-height:44px}}
@media(max-width:560px){.library-notice-overlay{padding:10px}.library-notice-dialog{padding:18px}.library-notice-dialog h2{font-size:19px}.library-notice-dialog p{font-size:13px}.library-notice-close{width:44px;height:44px}.library-authorized-reminder{font-size:12px}.library-notice-actions{flex-direction:column-reverse}.library-notice-btn{width:100%;min-height:44px}}
`;document.head.appendChild(s)}
function insertReminder(forcedLang){if(document.querySelector('.library-authorized-reminder'))return;const lang=langOf(forcedLang),c=copy(lang);const bar=document.createElement('div');bar.className='library-authorized-reminder';bar.setAttribute('role','note');bar.dir=lang==='ar'?'rtl':'ltr';bar.textContent=c.reminder;document.body.prepend(bar);document.body.classList.add('library-has-authorized-reminder')}
function showModal(mode,forcedLang,trigger){addStyles();const lang=langOf(forcedLang),c=copy(lang);return new Promise(resolve=>{let settled=false;const active=trigger||document.activeElement;const previousOverflow=document.body.style.overflow;const overlay=document.createElement('div');overlay.className='library-notice-overlay';overlay.innerHTML=`<div class="library-notice-dialog" role="dialog" aria-modal="true" aria-labelledby="libraryNoticeTitle" aria-describedby="libraryNoticeText" dir="${lang==='ar'?'rtl':'ltr'}"><button class="library-notice-close" type="button" aria-label="${c.close}">×</button><h2 id="libraryNoticeTitle">${c.openTitle}</h2><p id="libraryNoticeText"></p><div class="library-notice-actions"><button class="library-notice-btn secondary" type="button" data-notice-cancel>${c.cancel}</button><button class="library-notice-btn primary" type="button" data-notice-agree>${mode==='pack'?c.packAgree:c.agree}</button></div></div>`;
overlay.querySelector('#libraryNoticeText').textContent=c.text;document.body.appendChild(overlay);document.body.classList.add('library-notice-lock');document.body.style.overflow='hidden';
const dialog=overlay.firstElementChild,agree=overlay.querySelector('[data-notice-agree]'),cancel=overlay.querySelector('[data-notice-cancel]'),close=overlay.querySelector('.library-notice-close');
const focusables=()=>Array.from(dialog.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')).filter(el=>!el.disabled);
function finish(ok){if(settled)return;settled=true;document.removeEventListener('keydown',onKey,true);overlay.remove();document.body.classList.remove('library-notice-lock');document.body.style.overflow=previousOverflow;if(active&&active.focus&&document.contains(active))requestAnimationFrame(()=>active.focus());resolve(ok)}
function onKey(e){if(e.key==='Escape'){e.preventDefault();finish(false);return}if(e.key!=='Tab')return;const els=focusables();if(!els.length){e.preventDefault();return}const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
agree.addEventListener('click',()=>{if(mode==='reference')storeReferenceAgreement();finish(true)});cancel.addEventListener('click',()=>finish(false));close.addEventListener('click',()=>finish(false));overlay.addEventListener('mousedown',e=>{if(e.target===overlay)finish(false)});document.addEventListener('keydown',onKey,true);requestAnimationFrame(()=>agree.focus());
})}
function confirmReference(opts){opts=opts||{};if(hasReferenceAgreement())return Promise.resolve(true);return showModal('reference',opts.lang,opts.trigger)}
function confirmPack(opts){opts=opts||{};return showModal('pack',opts.lang,opts.trigger)}
function libraryHref(lang){const inSub=/\/cheatsheets(?:-en)?\//.test(location.pathname);return (inSub?'../':'')+(lang==='ar'?'library.html':'library-en.html')}
function showBlocked(forcedLang){const lang=langOf(forcedLang),c=copy(lang);document.documentElement.classList.remove('library-guard-pending');document.body.className='';document.body.innerHTML=`<main class="library-direct-blocked" dir="${lang==='ar'?'rtl':'ltr'}"><div><h1>${c.blockedTitle}</h1><p>${c.blockedText}</p><a href="${libraryHref(lang)}">${c.back}</a></div></main>`}
function directInit(){addStyles();document.documentElement.classList.add('library-guard-pending');const run=async()=>{const lang=langOf();if(hasReferenceAgreement()){document.documentElement.classList.remove('library-guard-pending');insertReminder(lang);return}const ok=await showModal('reference',lang,null);if(ok){document.documentElement.classList.remove('library-guard-pending');insertReminder(lang)}else showBlocked(lang)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run()}
document.addEventListener('click',async e=>{const a=e.target.closest?.('[data-library-pdf-download]');if(!a||a.dataset.noticeBypass==='1')return;if(hasReferenceAgreement())return;e.preventDefault();const ok=await confirmReference({lang:langOf(),trigger:a});if(!ok)return;const clone=document.createElement('a');clone.href=a.href;clone.download=a.download||'';clone.style.display='none';document.body.appendChild(clone);clone.click();clone.remove()},true);
window.LibraryNotice={confirmReference,confirmPack,hasReferenceAgreement,insertReminder};
if(DIRECT)directInit();
})();
